PImage img1, img2, img1a, img2a, img3 , img3a, img4, img4a, img5;
int var=0;

void setup(){
  size(1000,1000);
  img1 = loadImage("img1.png");
  img1a = loadImage("Img1a.png");
  img2 = loadImage("img2.png");
  img2a = loadImage("img2a.png");
  img3 = loadImage("img3.png");
  img3a = loadImage("img3a.png");
  img4 = loadImage("img4.png");
  img4a = loadImage("img4a.png");
  img5 = loadImage("img5.png");
}

void draw(){
  background(7,3,36);
  image(img5,200,200,600,600);
  image(img1a,0,0,200,200);
  image(img2a,800,0,200,200);
  image(img3a,0,800,200,200);
  image(img4a,800,800,200,200);

  if (var==1) image(img1,200,200,600,600);
  if (var==2) image(img2,200,200,600,600);
  if (var==3) image(img3,200,200,600,600);
  if (var==4) image(img4,200,200,600,600);
}

void mousePressed(){
  if((mouseX>0) && (mouseY>0) && (mouseX<200) && (mouseY<200)) var=1; else
  if((mouseX>800) && (mouseY>0) && (mouseX<1000) && (mouseY<200)) var=2; else
  if((mouseX>0) && (mouseY>800) && (mouseX<200) && (mouseY<1000)) var=3; else
  if((mouseX>800) && (mouseY>800) && (mouseX<1000) && (mouseY<1000)) var=4; else var=0;
}
