PImage img1, img2, img1a, img2a, img3 , img3a, img4, img4a, img5;
int var=0;

void setup(){
  size(700,700);
  img1 = loadImage("img1.png");
  img1a = loadImage("Img1a.png");
  img2 = loadImage("img2.png");
  img2a = loadImage("img2a.png");
  img3 = loadImage("img3.png");
  img3a = loadImage("img3a.png");
  img4 = loadImage("img4.png");
  img4a = loadImage("img4a.png");
  img5 = loadImage("img5.png");
}

void draw(){
  background(7,3,36);
  image(img5,100,100,500,500);
  image(img1a,0,0,100,100);
  image(img2a,600,0,100,100);
  image(img3a,0,600,100,100);
  image(img4a,600,600,100,100);

  if (var==1) image(img1,100,100,500,500);
  if (var==2) image(img2,100,100,500,500);
  if (var==3) image(img3,100,100,500,500);
  if (var==4) image(img4,100,100,500,500);
}

void mousePressed(){
  if((mouseX>0) && (mouseY>0) && (mouseX<100) && (mouseY<100)) var=1; else
  if((mouseX>600) && (mouseY>0) && (mouseX<800) && (mouseY<100)) var=2; else
  if((mouseX>0) && (mouseY>600) && (mouseX<100) && (mouseY<800)) var=3; else
  if((mouseX>600) && (mouseY>600) && (mouseX<800) && (mouseY<800)) var=4; else var=0;
}
